# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/shake/Documents/ut/spring2022/cs378h-botics/final-project/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/shake/Documents/ut/spring2022/cs378h-botics/final-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/shake/Documents/ut/spring2022/cs378h-botics/final-project/CMakeFiles /mnt/c/Users/shake/Documents/ut/spring2022/cs378h-botics/final-project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/shake/Documents/ut/spring2022/cs378h-botics/final-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simple_ba

# Build rule for target.
simple_ba: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple_ba
.PHONY : simple_ba

# fast build rule for target.
simple_ba/fast:
	$(MAKE) -f CMakeFiles/simple_ba.dir/build.make CMakeFiles/simple_ba.dir/build
.PHONY : simple_ba/fast

#=============================================================================
# Target rules for targets named bundle_adjuster

# Build rule for target.
bundle_adjuster: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bundle_adjuster
.PHONY : bundle_adjuster

# fast build rule for target.
bundle_adjuster/fast:
	$(MAKE) -f CMakeFiles/bundle_adjuster.dir/build.make CMakeFiles/bundle_adjuster.dir/build
.PHONY : bundle_adjuster/fast

#=============================================================================
# Target rules for targets named bundle_adjustment_test

# Build rule for target.
bundle_adjustment_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bundle_adjustment_test
.PHONY : bundle_adjustment_test

# fast build rule for target.
bundle_adjustment_test/fast:
	$(MAKE) -f CMakeFiles/bundle_adjustment_test.dir/build.make CMakeFiles/bundle_adjustment_test.dir/build
.PHONY : bundle_adjustment_test/fast

bal_problem.o: bal_problem.cc.o

.PHONY : bal_problem.o

# target to build an object file
bal_problem.cc.o:
	$(MAKE) -f CMakeFiles/bundle_adjuster.dir/build.make CMakeFiles/bundle_adjuster.dir/bal_problem.cc.o
.PHONY : bal_problem.cc.o

bal_problem.i: bal_problem.cc.i

.PHONY : bal_problem.i

# target to preprocess a source file
bal_problem.cc.i:
	$(MAKE) -f CMakeFiles/bundle_adjuster.dir/build.make CMakeFiles/bundle_adjuster.dir/bal_problem.cc.i
.PHONY : bal_problem.cc.i

bal_problem.s: bal_problem.cc.s

.PHONY : bal_problem.s

# target to generate assembly for a file
bal_problem.cc.s:
	$(MAKE) -f CMakeFiles/bundle_adjuster.dir/build.make CMakeFiles/bundle_adjuster.dir/bal_problem.cc.s
.PHONY : bal_problem.cc.s

bundle_adjuster.o: bundle_adjuster.cc.o

.PHONY : bundle_adjuster.o

# target to build an object file
bundle_adjuster.cc.o:
	$(MAKE) -f CMakeFiles/bundle_adjuster.dir/build.make CMakeFiles/bundle_adjuster.dir/bundle_adjuster.cc.o
.PHONY : bundle_adjuster.cc.o

bundle_adjuster.i: bundle_adjuster.cc.i

.PHONY : bundle_adjuster.i

# target to preprocess a source file
bundle_adjuster.cc.i:
	$(MAKE) -f CMakeFiles/bundle_adjuster.dir/build.make CMakeFiles/bundle_adjuster.dir/bundle_adjuster.cc.i
.PHONY : bundle_adjuster.cc.i

bundle_adjuster.s: bundle_adjuster.cc.s

.PHONY : bundle_adjuster.s

# target to generate assembly for a file
bundle_adjuster.cc.s:
	$(MAKE) -f CMakeFiles/bundle_adjuster.dir/build.make CMakeFiles/bundle_adjuster.dir/bundle_adjuster.cc.s
.PHONY : bundle_adjuster.cc.s

bundle_adjustment_test.o: bundle_adjustment_test.cpp.o

.PHONY : bundle_adjustment_test.o

# target to build an object file
bundle_adjustment_test.cpp.o:
	$(MAKE) -f CMakeFiles/bundle_adjustment_test.dir/build.make CMakeFiles/bundle_adjustment_test.dir/bundle_adjustment_test.cpp.o
.PHONY : bundle_adjustment_test.cpp.o

bundle_adjustment_test.i: bundle_adjustment_test.cpp.i

.PHONY : bundle_adjustment_test.i

# target to preprocess a source file
bundle_adjustment_test.cpp.i:
	$(MAKE) -f CMakeFiles/bundle_adjustment_test.dir/build.make CMakeFiles/bundle_adjustment_test.dir/bundle_adjustment_test.cpp.i
.PHONY : bundle_adjustment_test.cpp.i

bundle_adjustment_test.s: bundle_adjustment_test.cpp.s

.PHONY : bundle_adjustment_test.s

# target to generate assembly for a file
bundle_adjustment_test.cpp.s:
	$(MAKE) -f CMakeFiles/bundle_adjustment_test.dir/build.make CMakeFiles/bundle_adjustment_test.dir/bundle_adjustment_test.cpp.s
.PHONY : bundle_adjustment_test.cpp.s

simple_ba.o: simple_ba.cc.o

.PHONY : simple_ba.o

# target to build an object file
simple_ba.cc.o:
	$(MAKE) -f CMakeFiles/simple_ba.dir/build.make CMakeFiles/simple_ba.dir/simple_ba.cc.o
.PHONY : simple_ba.cc.o

simple_ba.i: simple_ba.cc.i

.PHONY : simple_ba.i

# target to preprocess a source file
simple_ba.cc.i:
	$(MAKE) -f CMakeFiles/simple_ba.dir/build.make CMakeFiles/simple_ba.dir/simple_ba.cc.i
.PHONY : simple_ba.cc.i

simple_ba.s: simple_ba.cc.s

.PHONY : simple_ba.s

# target to generate assembly for a file
simple_ba.cc.s:
	$(MAKE) -f CMakeFiles/simple_ba.dir/build.make CMakeFiles/simple_ba.dir/simple_ba.cc.s
.PHONY : simple_ba.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... simple_ba"
	@echo "... bundle_adjuster"
	@echo "... bundle_adjustment_test"
	@echo "... bal_problem.o"
	@echo "... bal_problem.i"
	@echo "... bal_problem.s"
	@echo "... bundle_adjuster.o"
	@echo "... bundle_adjuster.i"
	@echo "... bundle_adjuster.s"
	@echo "... bundle_adjustment_test.o"
	@echo "... bundle_adjustment_test.i"
	@echo "... bundle_adjustment_test.s"
	@echo "... simple_ba.o"
	@echo "... simple_ba.i"
	@echo "... simple_ba.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

